name: Build

on: [pull_request]

jobs:
  build:
    name: Build & Test
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Delete Package Cache
        run: swift package reset
      - name: Build Package
        run: swift build
      - name: Test Package
        run: swift test
