name: Versioning & Release

on:
  push:
    branches:
      - main

jobs:
  versioning-and-release:
    name: Versioning & Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Conventional CHANGELOG
        uses: TriPSs/conventional-changelog-action@v3.17.0
        id: changelog
        with:
          github-token: ${{ secrets.ACCESS_TOKEN }}
          git-message: 'release: {version}'
          git-user-name: ${{ secrets.USERNAME }}
          git-user-email: ${{ secrets.EMAIL }}
          tag-prefix: ''
          output-file: 'CHANGELOG.md'
          release-count: 0
          skip-version-file: 'true'
          skip-commit: 'false'
      - name: Create Release
        uses: ncipollo/release-action@v1.11.1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        token: ${{ secrets.ACCESS_TOKEN }}
        tag: ${{ steps.changelog.outputs.tag }}
        name: ${{ steps.changelog.outputs.tag }}
        body: ${{ steps.changelog.outputs.clean_changelog }}
